### ISSUE TITLE
Values for input to function to produce example waves ?

### ISSUE THREAD

**Issue by thomasclifford** [labay11/tunneling-simulation#1]
Labay11, thank you for your work on this.
Do you have examples of the 6 input numbers you used for the examples ?
The png filenames have 4 numbers each, but there are 6 values to enter for starting the 
simulation.

Thanks again.
Tom C.

**Comment by labay11** [comment]
Sorry, I used a different version to create those files and I though it was explained here too. The filename correspond to: 'x_xx_y_yy.png'
- V0: energy of the potential barrier up to 2 digits of precision, x.xx encoded as x_xx
- T: energy of the kick up to 2 digits of precision, y.yy encoded as y_yy

**Comment by thomasclifford** [comment]
I have not looked at all the code yet, but do you default the other 4 values 
for the constructor (L, l, xi, sigmax) to constants or are they computed from V0 and T?
I'll be able to look at more of the code tomorrow.
Thanks for your help.

**Comment by labay11** [comment]
No, the other variables take the value that you want and are constant. From the images you can see that I used L=8 and l=0.6 with xi=-L/2 and sigmax=0.6

**Comment by thomasclifford** [comment]
Ok, Thank you. I'll have to research the Schrodinger equation more to get a better feel for what the values represent.Thanks again.

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 14, 2018 at 10:28 PM, labay11<notifications@github.com> wrote:   
No, the other variables take the value that you want and are constant. From the images you can see that I used L=8 and l=0.6 with xi=-L/2 and sigmax=0.6
